f = open('frontend/pages/admin/dashboard.html', 'r', encoding='utf-8')
c = f.read()
f.close()
c = c.replace('href="../css/style.css"', 'href="../../css/style.css"')
c = c.replace('src="../js/app.js"', 'src="../../js/app.js"')
c = c.replace('href="css/style.css"', 'href="../../css/style.css"')
c = c.replace('src="js/app.js"', 'src="../../js/app.js"')
f = open('frontend/pages/admin/dashboard.html', 'w', encoding='utf-8')
f.write(c)
f.close()
print('Paths fixed!')
