from app import app, db
from models import Question
import json

app.app_context().push()
print(f"Current: {Question.query.count()} questions")

qs = [
    {"category":"safety","difficulty":"easy","question_text":"What IP rating for bathroom zone 0?","options":json.dumps(["IPX7","IPX4","IPX5","IP44"]),"correct_answer":"IPX7","explanation":"Zone 0 inside bath needs IPX7 immersion protection.","regulation_reference":"BS 7671 Section 701","practical_tip":"Zone 0 = inside bath. IPX7 = submersion proof.","epra_class":"Class C"},
    {"category":"safety","difficulty":"medium","question_text":"Safe isolation procedure steps?","options":json.dumps(["Prove dead,lock off,keep key,test tester,prove dead again","Switch off MCB and start work","Remove fuse and tape switch","Tell someone to watch board"]),"correct_answer":"Prove dead,lock off,keep key,test tester,prove dead again","explanation":"Must prove dead BEFORE and AFTER locking off.","regulation_reference":"EAWR 1989","practical_tip":"Test voltage tester on known live source first!","epra_class":"Class C"},
    {"category":"safety","difficulty":"hard","question_text":"Max Zs for 6A Type C MCB TN 230V?","options":json.dumps(["3.83ohm","7.67ohm","1.92ohm","5.75ohm"]),"correct_answer":"3.83ohm","explanation":"Zs=230/(6x10)=3.83ohm","regulation_reference":"BS 7671 Table 41.3","practical_tip":"Type C=10x In. Type B=5x. Type D=20x.","epra_class":"Class B"},
    {"category":"safety","difficulty":"medium","question_text":"Fire class for flammable liquids?","options":json.dumps(["Class B","Class A","Class C","Class D"]),"correct_answer":"Class B","explanation":"Class B = flammable liquids like petrol, oil, paint.","regulation_reference":"BS EN 2","practical_tip":"A=Ash B=Boil C=Current D=Metal F=Cooking oil","epra_class":"Class C"},
    {"category":"installation","difficulty":"easy","question_text":"Min bend radius armoured cable?","options":json.dumps(["8x cable diameter","6x cable diameter","4x cable diameter","10x cable diameter"]),"correct_answer":"8x cable diameter","explanation":"SWA needs 8x due to steel wire armour.","regulation_reference":"BS 7671 522.8","practical_tip":"SWA tough but kinks if bent too tight!","epra_class":"Class C"},
    {"category":"installation","difficulty":"medium","question_text":"Min depth buried cable no protection?","options":json.dumps(["600mm","450mm","300mm","750mm"]),"correct_answer":"600mm","explanation":"Direct buried needs 600mm cover minimum.","regulation_reference":"BS 7671 522.8.10","practical_tip":"Use marker tape above buried cables!","epra_class":"Class C"},
    {"category":"installation","difficulty":"hard","question_text":"Current capacity 2.5mm2 clipped direct?","options":json.dumps(["27A","20A","24A","32A"]),"correct_answer":"27A","explanation":"2.5mm2 Method C = 27A. In insulation = 18.5A.","regulation_reference":"BS 7671 Table 4D5","practical_tip":"Method changes capacity drastically! Check tables.","epra_class":"Class B"},
    {"category":"testing","difficulty":"medium","question_text":"IR test voltage for 230V circuit?","options":json.dumps(["500V DC","250V DC","1000V DC","230V AC"]),"correct_answer":"500V DC","explanation":"500V DC for circuits up to 500V nominal.","regulation_reference":"BS 7671 643.3","practical_tip":"500V stresses insulation safely.","epra_class":"Class C"},
    {"category":"testing","difficulty":"easy","question_text":"First test in sequence?","options":json.dumps(["Continuity","Insulation resistance","Polarity","Earth loop"]),"correct_answer":"Continuity","explanation":"Continuity first in CIPELR - done DEAD.","regulation_reference":"BS 7671 Part 6","practical_tip":"CIPELR: Continuity, IR, Polarity, Earth Loop, RCD.","epra_class":"Class C"},
    {"category":"testing","difficulty":"hard","question_text":"30mA RCD trip time at 1x?","options":json.dumps(["300ms","200ms","40ms","500ms"]),"correct_answer":"300ms","explanation":"300ms at 1x. 40ms at 5x (150mA).","regulation_reference":"BS 7671 Table 3A","practical_tip":"Test at 0, 180, 1x, and 5x for complete check.","epra_class":"Class B"},
    {"category":"kenya_power","difficulty":"easy","question_text":"Kenya Power supply frequency?","options":json.dumps(["50Hz","60Hz","50/60Hz","100Hz"]),"correct_answer":"50Hz","explanation":"Kenya uses 50Hz per British/IEC standard.","regulation_reference":"Kenya Power Standards","practical_tip":"Most appliances work on 50Hz. Check imports!","epra_class":"Class C"},
    {"category":"kenya_power","difficulty":"medium","question_text":"Standard domestic single-phase capacity?","options":json.dumps(["60A","30A","100A","40A"]),"correct_answer":"60A","explanation":"Standard domestic = 60A single phase.","regulation_reference":"Kenya Power","practical_tip":"Need more? Apply for 3-phase.","epra_class":"Class C"},
    {"category":"kenya_power","difficulty":"easy","question_text":"Kenya Power earthing system?","options":json.dumps(["TN-C-S (PME)","TT","TN-S","IT"]),"correct_answer":"TN-C-S (PME)","explanation":"Protective Multiple Earthing system.","regulation_reference":"Kenya Power Standards","practical_tip":"PME = neutral+earth combined at service head.","epra_class":"Class C"},
    {"category":"calculations","difficulty":"hard","question_text":"Zs for 32A Type B MCB TN 230V?","options":json.dumps(["1.44ohm","1.15ohm","0.72ohm","2.30ohm"]),"correct_answer":"1.44ohm","explanation":"Zs=230/(32x5)=1.44ohm","regulation_reference":"BS 7671 Table 41.3","practical_tip":"Design Zs = measured Zs x 0.8 for temp.","epra_class":"Class B"},
    {"category":"calculations","difficulty":"medium","question_text":"Current for 3kW heater at 240V?","options":json.dumps(["12.5A","10A","15A","8A"]),"correct_answer":"12.5A","explanation":"I=P/V=3000/240=12.5A","regulation_reference":"Ohms Law","practical_tip":"Heaters are resistive - power factor = 1.","epra_class":"Class C"},
    {"category":"calculations","difficulty":"hard","question_text":"Voltage drop 4mm2 30A 25m (mV/A/m=11)","options":json.dumps(["8.25V","6.5V","10.2V","5.75V"]),"correct_answer":"8.25V","explanation":"Vd=(11x30x25)/1000=8.25V = 3.4%","regulation_reference":"BS 7671 App 4","practical_tip":"4mm2 good for long runs.","epra_class":"Class B"},
    {"category":"calculations","difficulty":"easy","question_text":"Power of 230V 10A resistive load?","options":json.dumps(["2300W","4600W","1150W","23W"]),"correct_answer":"2300W","explanation":"P=VxI=230x10=2300W","regulation_reference":"Ohms Law","practical_tip":"P=VI resistive. P=VIxpf for motors.","epra_class":"Class C"},
    {"category":"earthing","difficulty":"medium","question_text":"Purpose of earthing?","options":json.dumps(["Connect to earth for safety","Increase voltage","Reduce current","Improve power factor"]),"correct_answer":"Connect to earth for safety","explanation":"Earthing provides fault current path.","regulation_reference":"BS 7671","practical_tip":"Without earth, fault = live metal indefinitely!","epra_class":"Class C"},
    {"category":"earthing","difficulty":"hard","question_text":"Max Ra for 30mA RCD TT system?","options":json.dumps(["1667ohm","500ohm","1000ohm","3333ohm"]),"correct_answer":"1667ohm","explanation":"Ra<50/0.03=1667ohm. Aim for <200ohm.","regulation_reference":"BS 7671 411.5","practical_tip":"Lower Ra = safer. Aim <200ohm in practice.","epra_class":"Class B"},
    {"category":"regulations","difficulty":"easy","question_text":"BS 7671 commonly called?","options":json.dumps(["IEE Wiring Regulations","Building Code","Kenya Standard","IEC 60364"]),"correct_answer":"IEE Wiring Regulations","explanation":"BS 7671 = IEE Wiring Regulations 18th Edition.","regulation_reference":"BS 7671","practical_tip":"BS 7671 is the electrician bible!","epra_class":"Class C"},
    {"category":"regulations","difficulty":"medium","question_text":"EPRA full form Kenya?","options":json.dumps(["Energy and Petroleum Regulatory Authority","Electrical Power Regulation Agency","Energy Production and Regulation Authority","Electrical Petroleum Regulatory Agency"]),"correct_answer":"Energy and Petroleum Regulatory Authority","explanation":"EPRA regulates energy and petroleum in Kenya.","regulation_reference":"Energy Act 2019","practical_tip":"EPRA licenses electricians in Kenya!","epra_class":"Class C"},
    {"category":"regulations","difficulty":"medium","question_text":"Electrician license for domestic?","options":json.dumps(["Class C","Class A","Class B","Class D"]),"correct_answer":"Class C","explanation":"Class C = domestic. B = commercial. A = HV.","regulation_reference":"EPRA Regulations","practical_tip":"Start Class C, work up to B and A.","epra_class":"Class C"},
]

added = 0
for q in qs:
    if not Question.query.filter_by(question_text=q["question_text"]).first():
        db.session.add(Question(**q))
        added += 1
db.session.commit()
print(f"Added {added} new questions! Total: {Question.query.count()}")
cats = db.session.query(Question.category, db.func.count(Question.id)).group_by(Question.category).all()
for c, n in cats:
    print(f"  {c}: {n}")

